fNumber = eval(input())
print("{:.2f}".format(fNumber))
print("{:e} {:E} {:.2f}%".format(fNumber, fNumber, fNumber * 100))
iNumber = eval(input())
print("{:b} {:x}".format(iNumber, iNumber))
st = input()
st = st.strip()
print(st.upper())
print("{:>20}".format(st))
print("{:*^20}".format(st))
print("{} + {} = {}".format(fNumber, iNumber, fNumber + iNumber))
