a=eval(input())
b=eval(input())
c=input()
print("{:.2f}".format(a))
print("{0:e} {0:E} {0:.2%}".format(a))
print("{0:b} {0:x}".format(b))
c=c.strip()
print(c.upper())
print("{:>20}".format(c))
print("{:*^20}".format(c))
print("{0} + {1} = {2}".format(a,b,a+b))