classA = set(list(input()))
classB = set(input().split())
ACM = set(input().split())
English = set(input().split())
zhuan = input()
print("Total: {}".format(len(classA) + len(classB)))
classAll = classA.union(classB)
print("Not in race: {}, num: {}".format(sorted(classAll.difference(ACM.union(English))),len(classAll.difference(ACM.union(English)))))
print("All racers: {}, num: {}".format(sorted(ACM.union(English)),len(ACM.union(English))))
print("ACM + English: {}, num: {}".format(sorted(ACM.intersection(English)),len(ACM.intersection(English))))
print("Only ACM: {}".format(sorted(ACM.difference(English))))
print("Only English: {}".format(sorted(English.difference(ACM))))
print("ACM Or English: {}".format(sorted(English.union(ACM).difference(ACM.intersection(English)))))
if zhuan in classA:
    classA.remove(zhuan)
    print(sorted(classA))
elif zhuan in classB:
    classB.remove(zhuan)
    print(sorted(classB))